<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="WolverineFx.Postgresql" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yestino.Common\Yestino.Common.csproj" />
    <ProjectReference Include="..\Yestino.OrderingContracts\Yestino.OrderingContracts.csproj" />
    <ProjectReference Include="..\Yestino.ProductCatalogContracts\Yestino.ProductCatalogContracts.csproj" />
    <ProjectReference Include="..\Yestino.WarehouseContracts\Yestino.WarehouseContracts.csproj" />
  </ItemGroup>

</Project>
